<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sensei" failures="1" tests="2" name="Parallel Tests" time="14.502" errors="0" timestamp="2023-02-17T12:17:34 IST">
  <testcase classname="Tests.Tests" name="matchReleaseDate" time="10.258">
    <failure type="java.lang.AssertionError" message="expected [17 December 2021] but found [December 17, 2021 (United States)]">
      <![CDATA[java.lang.AssertionError: expected [17 December 2021] but found [December 17, 2021 (United States)]
at Tests.Tests.matchReleaseDate(Tests.java:43)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- matchReleaseDate -->
  <testcase classname="Tests.Tests" name="matchCountryOrigin" time="10.258"/>
</testsuite> <!-- Parallel Tests -->
